vim.o.bg = "dark"
vim.o.breakindent = true
vim.o.cc = "100"
vim.o.cindent = true
vim.o.cinoptions = "1s"
vim.o.compatible = false
vim.o.completeopt = "menuone,noselect"
vim.o.confirm = true
vim.o.cursorline = true
vim.o.cursorlineopt = "number"
vim.o.errorbells = true
vim.o.expandtab = true
vim.o.hlsearch = false
vim.o.ignorecase = true
vim.o.incsearch = true
vim.o.linebreak = true
vim.o.mouse = ""
vim.o.number = true
vim.o.scrollback = 9001
vim.o.scrolloff = 8
vim.o.shiftwidth = 0
vim.o.showmatch = true
vim.o.smartcase = true
vim.o.spell = true
vim.o.tabstop = 4
vim.o.timeoutlen=1000
vim.o.title = true
vim.o.titlestring = "%F - Neovim"
vim.o.undofile = true
vim.o.updatetime = 250
vim.o.wildmenu = true
vim.o.wrap = true

